/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebas;

import javax.swing.JOptionPane;

/**
 *
 * @author Marco Antonio
 */
public class vocales extends javax.swing.JFrame {

    /**
     * Creates new form vocales
     */
    public vocales() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        btncantidad = new javax.swing.JButton();
        lblcantidad = new javax.swing.JTextField();
        btnmayusculas = new javax.swing.JButton();
        lblmayusculas = new javax.swing.JTextField();
        btnminusculas = new javax.swing.JButton();
        lblminusculas = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        of = new javax.swing.JRadioButton();
        botonon = new javax.swing.JRadioButton();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new java.awt.GridLayout(5, 1));

        btncantidad.setText("cantidad de letras");
        btncantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncantidadActionPerformed(evt);
            }
        });
        getContentPane().add(btncantidad);

        lblcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblcantidadActionPerformed(evt);
            }
        });
        getContentPane().add(lblcantidad);

        btnmayusculas.setText("mayusculas");
        btnmayusculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmayusculasActionPerformed(evt);
            }
        });
        getContentPane().add(btnmayusculas);
        getContentPane().add(lblmayusculas);

        btnminusculas.setText("minusculas");
        btnminusculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminusculasActionPerformed(evt);
            }
        });
        getContentPane().add(btnminusculas);
        getContentPane().add(lblminusculas);

        jButton3.setText("salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);

        of.setText("off");
        getContentPane().add(of);

        botonon.setText("on");
        getContentPane().add(botonon);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblcantidadActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btncantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncantidadActionPerformed
        // TODO add your handling code here:
        Pruebas p = new Pruebas  ();
        String a =lblcantidad.getText();
       if (botonon.isSelected()) {
    if (p.ValidarLetras(a)) {
        JOptionPane.showMessageDialog(null, "Es correcto, ingresaste letras.");
    } else {
        JOptionPane.showMessageDialog(null, "Es incorrecto, ingresaste números.");
    }
} else {
    JOptionPane.showMessageDialog(null, "La validación está desactivada.");
       }

    }//GEN-LAST:event_btncantidadActionPerformed

    private void btnmayusculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmayusculasActionPerformed
        // TODO add your handling code here:
              // TODO add your handling code here:
        Pruebas p = new Pruebas  ();
        String a =lblmayusculas.getText();
       if (botonon.isSelected()) {
    if (p.validarMAYUSCULAS(a)) {
    }
       }
    }//GEN-LAST:event_btnmayusculasActionPerformed

    private void btnminusculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminusculasActionPerformed
        // TODO add your handling code here:
               // TODO add your handling code here:
        Pruebas p = new Pruebas  ();
        String a =lblminusculas.getText();
       if (botonon.isSelected()) {
    if (p.validarMinusculas(a)) {
       
    }
       }
    }//GEN-LAST:event_btnminusculasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vocales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonon;
    private javax.swing.JButton btncantidad;
    private javax.swing.JButton btnmayusculas;
    private javax.swing.JButton btnminusculas;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField lblcantidad;
    private javax.swing.JTextField lblmayusculas;
    private javax.swing.JTextField lblminusculas;
    private javax.swing.JRadioButton of;
    // End of variables declaration//GEN-END:variables
}
