/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clase;

import javax.swing.JOptionPane;

/**
 *
 * @author ROASUS
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblContarLetras = new javax.swing.JLabel();
        lblConarMayusculas = new javax.swing.JLabel();
        lblContarMinusculas = new javax.swing.JLabel();
        lblInvertir = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        txtTexto = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        opMyusculas = new javax.swing.JRadioButton();
        jPanel19 = new javax.swing.JPanel();
        optMinusculas = new javax.swing.JRadioButton();
        jPanel20 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        btnMayus = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        lblMostrraMayusculas = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        lblMostrarMinusculas = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        bntMinus = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnContarL = new javax.swing.JButton();
        btnContarMayus = new javax.swing.JButton();
        btnContarMinus = new javax.swing.JButton();
        btnInvertir = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(4, 1));

        lblContarLetras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblContarLetras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContarLetras.setText("0");
        jPanel1.add(lblContarLetras);

        lblConarMayusculas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConarMayusculas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConarMayusculas.setText("0");
        jPanel1.add(lblConarMayusculas);

        lblContarMinusculas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblContarMinusculas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContarMinusculas.setText("0");
        jPanel1.add(lblContarMinusculas);

        lblInvertir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblInvertir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblInvertir);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 120));
        jPanel2.setLayout(new java.awt.GridLayout(3, 4));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel10);

        jPanel11.setLayout(new java.awt.GridLayout(1, 1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Escribe un texto");
        jPanel11.add(jLabel1);

        jPanel2.add(jPanel11);

        jPanel12.setLayout(new java.awt.GridLayout(1, 1));

        txtTexto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel12.add(txtTexto);

        jPanel2.add(jPanel12);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel13);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel14);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel15);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel16);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel17);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(100, 120));
        jPanel3.setLayout(new java.awt.GridLayout(2, 4));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel18);

        jPanel21.setLayout(new java.awt.GridLayout(1, 1));

        buttonGroup1.add(opMyusculas);
        opMyusculas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        opMyusculas.setText("Mayusculas");
        jPanel21.add(opMyusculas);

        jPanel3.add(jPanel21);

        jPanel19.setLayout(new java.awt.GridLayout(1, 1));

        buttonGroup1.add(optMinusculas);
        optMinusculas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        optMinusculas.setText("Minusculas");
        jPanel19.add(optMinusculas);

        jPanel3.add(jPanel19);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel20);

        jPanel22.setLayout(new java.awt.GridLayout(1, 1));

        btnMayus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMayus.setText("Cambiar Mayusculas");
        btnMayus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMayusActionPerformed(evt);
            }
        });
        jPanel22.add(btnMayus);

        jPanel3.add(jPanel22);

        jPanel23.setLayout(new java.awt.GridLayout(1, 1));

        lblMostrraMayusculas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel23.add(lblMostrraMayusculas);

        jPanel3.add(jPanel23);

        jPanel24.setLayout(new java.awt.GridLayout(1, 1));

        lblMostrarMinusculas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel24.add(lblMostrarMinusculas);

        jPanel3.add(jPanel24);

        jPanel25.setLayout(new java.awt.GridLayout(1, 1));

        bntMinus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bntMinus.setText("Cambiar Minusculas");
        bntMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMinusActionPerformed(evt);
            }
        });
        jPanel25.add(bntMinus);

        jPanel3.add(jPanel25);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setPreferredSize(new java.awt.Dimension(200, 150));
        jPanel4.setLayout(new java.awt.GridLayout(4, 1));

        btnContarL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnContarL.setText("contar Letras");
        btnContarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarLActionPerformed(evt);
            }
        });
        jPanel4.add(btnContarL);

        btnContarMayus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnContarMayus.setText("Contar Mayusculas");
        btnContarMayus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarMayusActionPerformed(evt);
            }
        });
        jPanel4.add(btnContarMayus);

        btnContarMinus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnContarMinus.setText("ContarMinusculas");
        btnContarMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarMinusActionPerformed(evt);
            }
        });
        jPanel4.add(btnContarMinus);

        btnInvertir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInvertir.setText("Invertir");
        btnInvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvertirActionPerformed(evt);
            }
        });
        jPanel4.add(btnInvertir);

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setPreferredSize(new java.awt.Dimension(10, 120));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarLActionPerformed
        // TODO add your handling code here:
        Validaciones val = new Validaciones();
        String a = txtTexto.getText();
        if (val.ValidarLetras(a)){
            int num = val.Conarletras(a);
            lblContarLetras.setText(Integer.toString(num));
        }else{
           JOptionPane.showMessageDialog(null, "Error");
        }
    
    }//GEN-LAST:event_btnContarLActionPerformed

    private void btnContarMayusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarMayusActionPerformed
        // TODO add your handling code here:
        Validaciones val = new Validaciones();
        String a = txtTexto.getText();
        if (val.ValidarLetras(a)){
            int num = val.Conarmayusculas(a);
            lblConarMayusculas.setText(Integer.toString(num));
        }else{
           JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_btnContarMayusActionPerformed

    private void btnContarMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarMinusActionPerformed
        // TODO add your handling code here:
        Validaciones val = new Validaciones();
        String a = txtTexto.getText();
        if (val.ValidarLetras(a)){
            int num = val.Conarminusculas(a);
            lblContarMinusculas.setText(Integer.toString(num));
        }else{
           JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_btnContarMinusActionPerformed

    private void btnInvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvertirActionPerformed
        // TODO add your handling code here:
        Validaciones val = new Validaciones();
        String a = txtTexto.getText();
        if (val.ValidarLetras(a)){
            String cad = Invertir(a);
            lblInvertir.setText(cad);
        }else{
           JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_btnInvertirActionPerformed

   private String Invertir(String x){
       String otracadena="";
       for (int i = x.length()-1; i >= 0; i--) {
           otracadena = otracadena + x.charAt(i);
       }
   
   return otracadena;
   }    
    
    
    
    private void btnMayusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMayusActionPerformed
        // TODO add your handling code here:
        Validaciones val = new Validaciones();
        String a = txtTexto.getText();
        if (val.ValidarLetras(a)){
            if (opMyusculas.isSelected()){
               lblMostrraMayusculas.setText(a.toUpperCase());
            }else{
            JOptionPane.showMessageDialog(null, "Elige un radiobutton");
            }
        }else{
           JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_btnMayusActionPerformed

    private void bntMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMinusActionPerformed
        // TODO add your handling code here:
       Validaciones val = new Validaciones();
        String a = txtTexto.getText();
        if (val.ValidarLetras(a)){
            if (optMinusculas.isSelected()){
              lblMostrarMinusculas.setText(a.toUpperCase());
            }else{
            JOptionPane.showMessageDialog(null, "Elige un radiobutton");
            }
        }else{
           JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_bntMinusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntMinus;
    private javax.swing.JButton btnContarL;
    private javax.swing.JButton btnContarMayus;
    private javax.swing.JButton btnContarMinus;
    private javax.swing.JButton btnInvertir;
    private javax.swing.JButton btnMayus;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblConarMayusculas;
    private javax.swing.JLabel lblContarLetras;
    private javax.swing.JLabel lblContarMinusculas;
    private javax.swing.JLabel lblInvertir;
    private javax.swing.JLabel lblMostrarMinusculas;
    private javax.swing.JLabel lblMostrraMayusculas;
    private javax.swing.JRadioButton opMyusculas;
    private javax.swing.JRadioButton optMinusculas;
    private javax.swing.JTextField txtTexto;
    // End of variables declaration//GEN-END:variables
}
